# Generated by Django 5.2.12 on 2026-03-21 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_user_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("treat_myself", "Treat Myself"),
                            ("glow_up", "Glow-Up Agenda"),
                            ("adulting", "Adulting\u2122"),
                            ("i_said_i_would", "I Said I Would"),
                            ("the_inevitable", "The Inevitable"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tag", models.CharField(blank=True, default="", max_length=255)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (0, "No one cares"),
                            (1, "No one is watching"),
                            (2, "I'll feel guilty"),
                            (3, "Others are watching"),
                            (4, "Others will be let down"),
                            (5, "I'll let myself down"),
                        ],
                        default=0,
                    ),
                ),
                ("recurring", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("list_id", models.IntegerField(blank=True, null=True)),
                ("muted_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="linked_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"],
                        name="core_task_user_id_0440f1_idx",
                    ),
                    models.Index(
                        fields=["user", "due_date"],
                        name="core_task_user_id_d96f3d_idx",
                    ),
                ],
            },
        ),
    ]
