# Generated by Django 5.2.12 on 2026-03-21 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list_id',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('treat_myself', 'Treat Myself'), ('glow_up', 'Glow-Up Agenda'), ('adulting', 'Adulting™'), ('i_said_i_would', 'I Said I Would'), ('the_inevitable', 'The Inevitable')], default='', max_length=30)),
                ('tag', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.IntegerField(choices=[(0, 'No one cares'), (1, 'No one is watching'), (2, "I'll feel guilty"), (3, 'Others are watching'), (4, 'Others will be let down'), (5, "I'll let myself down")], default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.list'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'sort_order'], name='core_list_user_id_800673_idx'),
        ),
    ]
