# Generated by Django 5.2.12 on 2026-03-22 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_task_list_id_list_task_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_id', models.IntegerField(blank=True, null=True)),
                ('recurrence_rule', models.TextField(blank=True, default='')),
                ('next_trigger_at', models.DateTimeField()),
                ('retry_interval_minutes', models.PositiveIntegerField()),
                ('persistent', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField()),
                ('triggered_at_bucket', models.DateTimeField()),
                ('attempt_number', models.PositiveIntegerField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.reminderschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(fields=['next_trigger_at', 'is_active'], name='core_remind_next_tr_4e5e62_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(fields=['user'], name='core_remind_user_id_c61519_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('habit_id__isnull', True), ('task__isnull', False)), models.Q(('habit_id__isnull', False), ('task__isnull', True)), _connector='OR'), name='reminder_schedule_task_xor_habit'),
        ),
        migrations.AddConstraint(
            model_name='reminderevent',
            constraint=models.UniqueConstraint(fields=('schedule', 'triggered_at_bucket'), name='unique_schedule_trigger_bucket'),
        ),
    ]
