# Generated by Django 5.2.12 on 2026-03-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devicetoken'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminderschedule',
            name='reminder_schedule_task_xor_habit',
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='core.list'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('habit_id__isnull', True), ('list__isnull', True), ('task__isnull', False)), models.Q(('habit_id__isnull', False), ('list__isnull', True), ('task__isnull', True)), models.Q(('habit_id__isnull', True), ('list__isnull', False), ('task__isnull', True)), _connector='OR'), name='reminder_schedule_task_xor_habit_xor_list'),
        ),
    ]
