# Generated by Django 5.2.12 on 2026-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stack_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
