# Generated by Django 5.2.12 on 2026-03-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_recurring_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderevent',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reminderevent',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderevent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
