# Generated by Django 5.2.12 on 2026-03-24 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reminderevent_body_reminderevent_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('reminder_times', models.JSONField(blank=True, default=list)),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('skipped', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reminderschedule',
            name='reminder_schedule_task_xor_habit_xor_list',
        ),
        migrations.RemoveField(
            model_name='reminderschedule',
            name='habit_id',
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='core.habit'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('habit__isnull', True), ('list__isnull', True), ('task__isnull', False)), models.Q(('habit__isnull', False), ('list__isnull', True), ('task__isnull', True)), models.Q(('habit__isnull', True), ('list__isnull', False), ('task__isnull', True)), _connector='OR'), name='reminder_schedule_task_xor_habit_xor_list'),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.habit'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user'], name='core_habit_user_id_24b84d_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'completed_at'], name='core_habitc_habit_i_fb21f0_idx'),
        ),
    ]
