# Generated by Django 5.2.12 on 2026-03-25 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_friendinvitation_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('remind_time', models.TimeField(blank=True, null=True)),
                ('recurrence', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='reminderschedule',
            name='reminder_schedule_task_xor_habit_xor_list',
        ),
        migrations.AddField(
            model_name='standalonereminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminderinstance',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.standalonereminder'),
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='standalone_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='core.standalonereminder'),
        ),
        migrations.AddConstraint(
            model_name='reminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('habit__isnull', True), ('list__isnull', True), ('standalone_reminder__isnull', True), ('task__isnull', False)), models.Q(('habit__isnull', False), ('list__isnull', True), ('standalone_reminder__isnull', True), ('task__isnull', True)), models.Q(('habit__isnull', True), ('list__isnull', False), ('standalone_reminder__isnull', True), ('task__isnull', True)), models.Q(('habit__isnull', True), ('list__isnull', True), ('standalone_reminder__isnull', False), ('task__isnull', True)), _connector='OR'), name='reminder_schedule_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='standalonereminder',
            index=models.Index(fields=['user', 'is_active'], name='core_standa_user_id_74a43a_idx'),
        ),
        migrations.AddConstraint(
            model_name='standalonereminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence__isnull', True), ('remind_at__isnull', False)), models.Q(('recurrence__isnull', False), ('remind_time__isnull', False)), _connector='OR'), name='standalone_reminder_time_required'),
        ),
        migrations.AddIndex(
            model_name='reminderinstance',
            index=models.Index(fields=['reminder', 'cleared_at'], name='core_remind_reminde_d78913_idx'),
        ),
    ]
