# Generated by Django 5.2.12 on 2026-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reminderinstance_standalonereminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('life_admin', 'Life Admin'), ('work', 'Work'), ('social', 'Social')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('life_admin', 'Life Admin'), ('work', 'Work'), ('social', 'Social')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0),
        ),
    ]
