# Generated by Django 5.2.12 on 2026-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_list_category_alter_list_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='focus_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='focus_sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'focus_date'], name='core_task_user_id_8ea4a7_idx'),
        ),
    ]
